apm install Hydrogen@2.3.0 &&
apm install atom-beautify@0.32.2 &&
apm install atom-ide-ui@0.9.3 &&
apm install atom-import-cost@1.2.0 &&
apm install atom-material-ui@2.1.3 &&
apm install busy-signal@1.4.3 &&
apm install css-declaration-sorter@1.2.0 &&
apm install docblockr@0.13.7 &&
apm install emmet@2.4.3 &&
apm install file-icons@2.1.15 &&
apm install git-blame@1.6.0 &&
apm install goto-definition@1.3.4 &&
apm install intentions@1.1.5 &&
apm install language-rspec@0.7.0 &&
apm install language-vue@0.23.1 &&
apm install linter@2.2.0 &&
apm install linter-eslint@8.4.1 &&
apm install linter-ui-default@1.7.1 &&
apm install minimap@4.29.8 &&
apm install node-debugger@1.10.1 &&
apm install nodejs-snippets@2.0.2 &&
apm install open-in-browsers@0.0.30 &&
apm install php-cs-fixer@4.1.1 &&
apm install php-debug@0.2.6 &&
apm install readme@2.0.0 &&
apm install split-diff@1.5.2 &&
apm install svg-preview@0.12.1 &&
apm install toggler@0.3.1 &&
apm install trailing-spaces@0.4.0 &&
apm install vue-snippets@0.6.0 &&
apm install vuejs2-snippets@0.15.0 &&
apm install xatom-debug@1.6.11 &&
apm install xatom-debug-chrome@0.7.4 &&
apm install xatom-debug-nodejs@0.9.3
